/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgetPasswordRouteImport } from './routes/forget-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TwoFactorIndexRouteImport } from './routes/two-factor/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation/$id'
import { Route as Auth_pathlessLayoutRouteRouteImport } from './routes/_auth/__pathlessLayout/route'
import { Route as TwoFactorOtpIndexRouteImport } from './routes/two-factor/otp/index'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts.$postId.index'
import { Route as DeviceSuccessIndexRouteImport } from './routes/device/success/index'
import { Route as DeviceDeniedIndexRouteImport } from './routes/device/denied/index'
import { Route as DeviceApproveIndexRouteImport } from './routes/device/approve/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as Auth_pathlessLayoutUnauthorizedRouteImport } from './routes/_auth/__pathlessLayout/unauthorized'
import { Route as Auth_pathlessLayoutResendRouteImport } from './routes/_auth/__pathlessLayout/resend'
import { Route as Auth_pathlessLayoutDashboardRouteImport } from './routes/_auth/__pathlessLayout/dashboard'
import { Route as PostsPostIdCommentsIndexRouteImport } from './routes/posts.$postId.comments.index'
import { Route as Auth_pathlessLayoutProfileIndexRouteImport } from './routes/_auth/__pathlessLayout/profile/index'
import { Route as Auth_pathlessLayoutAdminIndexRouteImport } from './routes/_auth/__pathlessLayout/admin/index'
import { Route as PostsPostIdCommentsCommentIdIndexRouteImport } from './routes/posts.$postId.comments.$commentId.index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgetPasswordRoute = ForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorIndexRoute = TwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_pathlessLayoutRouteRoute =
  Auth_pathlessLayoutRouteRouteImport.update({
    id: '/__pathlessLayout',
    getParentRoute: () => AuthRoute,
  } as any)
const TwoFactorOtpIndexRoute = TwoFactorOtpIndexRouteImport.update({
  id: '/two-factor/otp/',
  path: '/two-factor/otp/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DeviceSuccessIndexRoute = DeviceSuccessIndexRouteImport.update({
  id: '/device/success/',
  path: '/device/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceDeniedIndexRoute = DeviceDeniedIndexRouteImport.update({
  id: '/device/denied/',
  path: '/device/denied/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceApproveIndexRoute = DeviceApproveIndexRouteImport.update({
  id: '/device/approve/',
  path: '/device/approve/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_pathlessLayoutUnauthorizedRoute =
  Auth_pathlessLayoutUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => Auth_pathlessLayoutRouteRoute,
  } as any)
const Auth_pathlessLayoutResendRoute =
  Auth_pathlessLayoutResendRouteImport.update({
    id: '/resend',
    path: '/resend',
    getParentRoute: () => Auth_pathlessLayoutRouteRoute,
  } as any)
const Auth_pathlessLayoutDashboardRoute =
  Auth_pathlessLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Auth_pathlessLayoutRouteRoute,
  } as any)
const PostsPostIdCommentsIndexRoute =
  PostsPostIdCommentsIndexRouteImport.update({
    id: '/$postId/comments/',
    path: '/$postId/comments/',
    getParentRoute: () => PostsRouteRoute,
  } as any)
const Auth_pathlessLayoutProfileIndexRoute =
  Auth_pathlessLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => Auth_pathlessLayoutRouteRoute,
  } as any)
const Auth_pathlessLayoutAdminIndexRoute =
  Auth_pathlessLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => Auth_pathlessLayoutRouteRoute,
  } as any)
const PostsPostIdCommentsCommentIdIndexRoute =
  PostsPostIdCommentsCommentIdIndexRouteImport.update({
    id: '/$postId/comments/$commentId/',
    path: '/$postId/comments/$commentId/',
    getParentRoute: () => PostsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/forget-password': typeof ForgetPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/send': typeof ApiSendRoute
  '/device': typeof DeviceIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/two-factor': typeof TwoFactorIndexRoute
  '/dashboard': typeof Auth_pathlessLayoutDashboardRoute
  '/resend': typeof Auth_pathlessLayoutResendRoute
  '/unauthorized': typeof Auth_pathlessLayoutUnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/device/approve': typeof DeviceApproveIndexRoute
  '/device/denied': typeof DeviceDeniedIndexRoute
  '/device/success': typeof DeviceSuccessIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/two-factor/otp': typeof TwoFactorOtpIndexRoute
  '/admin': typeof Auth_pathlessLayoutAdminIndexRoute
  '/profile': typeof Auth_pathlessLayoutProfileIndexRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsIndexRoute
  '/posts/$postId/comments/$commentId': typeof PostsPostIdCommentsCommentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forget-password': typeof ForgetPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/send': typeof ApiSendRoute
  '/device': typeof DeviceIndexRoute
  '/posts': typeof PostsIndexRoute
  '/two-factor': typeof TwoFactorIndexRoute
  '/dashboard': typeof Auth_pathlessLayoutDashboardRoute
  '/resend': typeof Auth_pathlessLayoutResendRoute
  '/unauthorized': typeof Auth_pathlessLayoutUnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/device/approve': typeof DeviceApproveIndexRoute
  '/device/denied': typeof DeviceDeniedIndexRoute
  '/device/success': typeof DeviceSuccessIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/two-factor/otp': typeof TwoFactorOtpIndexRoute
  '/admin': typeof Auth_pathlessLayoutAdminIndexRoute
  '/profile': typeof Auth_pathlessLayoutProfileIndexRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsIndexRoute
  '/posts/$postId/comments/$commentId': typeof PostsPostIdCommentsCommentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forget-password': typeof ForgetPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_auth/__pathlessLayout': typeof Auth_pathlessLayoutRouteRouteWithChildren
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/api/send': typeof ApiSendRoute
  '/device/': typeof DeviceIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/two-factor/': typeof TwoFactorIndexRoute
  '/_auth/__pathlessLayout/dashboard': typeof Auth_pathlessLayoutDashboardRoute
  '/_auth/__pathlessLayout/resend': typeof Auth_pathlessLayoutResendRoute
  '/_auth/__pathlessLayout/unauthorized': typeof Auth_pathlessLayoutUnauthorizedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/device/approve/': typeof DeviceApproveIndexRoute
  '/device/denied/': typeof DeviceDeniedIndexRoute
  '/device/success/': typeof DeviceSuccessIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/two-factor/otp/': typeof TwoFactorOtpIndexRoute
  '/_auth/__pathlessLayout/admin/': typeof Auth_pathlessLayoutAdminIndexRoute
  '/_auth/__pathlessLayout/profile/': typeof Auth_pathlessLayoutProfileIndexRoute
  '/posts/$postId/comments/': typeof PostsPostIdCommentsIndexRoute
  '/posts/$postId/comments/$commentId/': typeof PostsPostIdCommentsCommentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/forget-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invitation/$id'
    | '/api/send'
    | '/device'
    | '/posts/'
    | '/two-factor'
    | '/dashboard'
    | '/resend'
    | '/unauthorized'
    | '/api/auth/$'
    | '/device/approve'
    | '/device/denied'
    | '/device/success'
    | '/posts/$postId'
    | '/two-factor/otp'
    | '/admin'
    | '/profile'
    | '/posts/$postId/comments'
    | '/posts/$postId/comments/$commentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forget-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invitation/$id'
    | '/api/send'
    | '/device'
    | '/posts'
    | '/two-factor'
    | '/dashboard'
    | '/resend'
    | '/unauthorized'
    | '/api/auth/$'
    | '/device/approve'
    | '/device/denied'
    | '/device/success'
    | '/posts/$postId'
    | '/two-factor/otp'
    | '/admin'
    | '/profile'
    | '/posts/$postId/comments'
    | '/posts/$postId/comments/$commentId'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_auth'
    | '/forget-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_auth/__pathlessLayout'
    | '/accept-invitation/$id'
    | '/api/send'
    | '/device/'
    | '/posts/'
    | '/two-factor/'
    | '/_auth/__pathlessLayout/dashboard'
    | '/_auth/__pathlessLayout/resend'
    | '/_auth/__pathlessLayout/unauthorized'
    | '/api/auth/$'
    | '/device/approve/'
    | '/device/denied/'
    | '/device/success/'
    | '/posts/$postId/'
    | '/two-factor/otp/'
    | '/_auth/__pathlessLayout/admin/'
    | '/_auth/__pathlessLayout/profile/'
    | '/posts/$postId/comments/'
    | '/posts/$postId/comments/$commentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgetPasswordRoute: typeof ForgetPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  ApiSendRoute: typeof ApiSendRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  TwoFactorIndexRoute: typeof TwoFactorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DeviceApproveIndexRoute: typeof DeviceApproveIndexRoute
  DeviceDeniedIndexRoute: typeof DeviceDeniedIndexRoute
  DeviceSuccessIndexRoute: typeof DeviceSuccessIndexRoute
  TwoFactorOtpIndexRoute: typeof TwoFactorOtpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forget-password': {
      id: '/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof ForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor/': {
      id: '/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/__pathlessLayout': {
      id: '/_auth/__pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Auth_pathlessLayoutRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/two-factor/otp/': {
      id: '/two-factor/otp/'
      path: '/two-factor/otp'
      fullPath: '/two-factor/otp'
      preLoaderRoute: typeof TwoFactorOtpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/device/success/': {
      id: '/device/success/'
      path: '/device/success'
      fullPath: '/device/success'
      preLoaderRoute: typeof DeviceSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/denied/': {
      id: '/device/denied/'
      path: '/device/denied'
      fullPath: '/device/denied'
      preLoaderRoute: typeof DeviceDeniedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/approve/': {
      id: '/device/approve/'
      path: '/device/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/__pathlessLayout/unauthorized': {
      id: '/_auth/__pathlessLayout/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof Auth_pathlessLayoutUnauthorizedRouteImport
      parentRoute: typeof Auth_pathlessLayoutRouteRoute
    }
    '/_auth/__pathlessLayout/resend': {
      id: '/_auth/__pathlessLayout/resend'
      path: '/resend'
      fullPath: '/resend'
      preLoaderRoute: typeof Auth_pathlessLayoutResendRouteImport
      parentRoute: typeof Auth_pathlessLayoutRouteRoute
    }
    '/_auth/__pathlessLayout/dashboard': {
      id: '/_auth/__pathlessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Auth_pathlessLayoutDashboardRouteImport
      parentRoute: typeof Auth_pathlessLayoutRouteRoute
    }
    '/posts/$postId/comments/': {
      id: '/posts/$postId/comments/'
      path: '/$postId/comments'
      fullPath: '/posts/$postId/comments'
      preLoaderRoute: typeof PostsPostIdCommentsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_auth/__pathlessLayout/profile/': {
      id: '/_auth/__pathlessLayout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof Auth_pathlessLayoutProfileIndexRouteImport
      parentRoute: typeof Auth_pathlessLayoutRouteRoute
    }
    '/_auth/__pathlessLayout/admin/': {
      id: '/_auth/__pathlessLayout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Auth_pathlessLayoutAdminIndexRouteImport
      parentRoute: typeof Auth_pathlessLayoutRouteRoute
    }
    '/posts/$postId/comments/$commentId/': {
      id: '/posts/$postId/comments/$commentId/'
      path: '/$postId/comments/$commentId'
      fullPath: '/posts/$postId/comments/$commentId'
      preLoaderRoute: typeof PostsPostIdCommentsCommentIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  PostsPostIdCommentsIndexRoute: typeof PostsPostIdCommentsIndexRoute
  PostsPostIdCommentsCommentIdIndexRoute: typeof PostsPostIdCommentsCommentIdIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  PostsPostIdCommentsIndexRoute: PostsPostIdCommentsIndexRoute,
  PostsPostIdCommentsCommentIdIndexRoute:
    PostsPostIdCommentsCommentIdIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface Auth_pathlessLayoutRouteRouteChildren {
  Auth_pathlessLayoutDashboardRoute: typeof Auth_pathlessLayoutDashboardRoute
  Auth_pathlessLayoutResendRoute: typeof Auth_pathlessLayoutResendRoute
  Auth_pathlessLayoutUnauthorizedRoute: typeof Auth_pathlessLayoutUnauthorizedRoute
  Auth_pathlessLayoutAdminIndexRoute: typeof Auth_pathlessLayoutAdminIndexRoute
  Auth_pathlessLayoutProfileIndexRoute: typeof Auth_pathlessLayoutProfileIndexRoute
}

const Auth_pathlessLayoutRouteRouteChildren: Auth_pathlessLayoutRouteRouteChildren =
  {
    Auth_pathlessLayoutDashboardRoute: Auth_pathlessLayoutDashboardRoute,
    Auth_pathlessLayoutResendRoute: Auth_pathlessLayoutResendRoute,
    Auth_pathlessLayoutUnauthorizedRoute: Auth_pathlessLayoutUnauthorizedRoute,
    Auth_pathlessLayoutAdminIndexRoute: Auth_pathlessLayoutAdminIndexRoute,
    Auth_pathlessLayoutProfileIndexRoute: Auth_pathlessLayoutProfileIndexRoute,
  }

const Auth_pathlessLayoutRouteRouteWithChildren =
  Auth_pathlessLayoutRouteRoute._addFileChildren(
    Auth_pathlessLayoutRouteRouteChildren,
  )

interface AuthRouteChildren {
  Auth_pathlessLayoutRouteRoute: typeof Auth_pathlessLayoutRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth_pathlessLayoutRouteRoute: Auth_pathlessLayoutRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgetPasswordRoute: ForgetPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  ApiSendRoute: ApiSendRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  TwoFactorIndexRoute: TwoFactorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DeviceApproveIndexRoute: DeviceApproveIndexRoute,
  DeviceDeniedIndexRoute: DeviceDeniedIndexRoute,
  DeviceSuccessIndexRoute: DeviceSuccessIndexRoute,
  TwoFactorOtpIndexRoute: TwoFactorOtpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
